http:
  routers:
    internal_router_a:
      service: internal_service_a
      rule: Host(`internal.mydomain.com`)
      tls:
        certResolver: default
  
  services:
    internal_service_a:
      loadBalancer:
        servers:
          - url: "https://192.168.0.123:8443"
# You can skip the following lines if the internal service isn't using https or you've configured traefik to trust your self signed certificate
        serversTransport: insecure
  
  serversTransports:
    insecure:
      insecureSkipVerify: true