entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"
    asDefault: true
    http2:
      maxConcurrentStreams: 250

api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
    network: traefik
  file:
    directory: /opt/traefik/config

certificatesResolvers:
  default:
    acme:
      email: myemail@me.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: ovh
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"